### PR TITLE
Fixed ExecutorServiceScheduler Future isDisposed always false

### LINKED ISSUE #22: Disposable future isDisposed will be always false
https://github.com/badoo/Reaktive/blob/bcba8b9ceeeb026d63f1304524234cba8abead17/reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/scheduler/ExecutorServiceScheduler.kt#L81

Should it be like that?

```kotlin
override val isDisposed: Boolean get() = isDone
```

### PR DESCRIPTION
**Pull request by arkivanov**
Fixes #22

### CODE REVIEW

File: reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/scheduler/ExecutorServiceScheduler.kt [hunk 1]
```diff
@@ -78,7 +78,7 @@ internal class ExecutorServiceScheduler(
         private companion object {
             private fun Future<*>.toDisposable(): Disposable =
                 object : Disposable {
-                    override val isDisposed: Boolean = isDone
+                    override val isDisposed: Boolean get() = isDone
```
Comment (lukaville) [inline reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/scheduler/ExecutorServiceScheduler.kt]: can we cover this change with a test?

Comment (arkivanov) [reply reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/scheduler/ExecutorServiceScheduler.kt]: We'll cover everything with tests soon, do you really want to cover this particular case?

Comment (lukaville) [reply reaktive/src/jvmCommonMain/kotlin/com/badoo/reaktive/scheduler/ExecutorServiceScheduler.kt]: okay, let's cover it later
okay
