### PR TITLE
Update replay after rxjava bug fix

### LINKED ISSUE #420: Inconsistency in behavior of replay
Hey.

I wrote a test and run it on both RxJava and Reaktive and observed different results. Here is the test:

```
@Test
fun testReplayRefCount() {
    val subject = BehaviorSubject.createDefault(false)
    val sharedStream = subject.replay(1).refCount(1)

    var disposable = sharedStream.test()
    subject.onNext(true)

    disposable.assertValues(false, true)
    disposable.dispose()

    disposable = sharedStream.test()
    subject.onNext(false)

    disposable.assertValues(true, false)
}
```

As you might guess, running this test with RxJava results in green, while with Reaktive - red.
Looks like on second subscription, the internal implementation of replay creates a new [ReplaySubject](https://github.com/badoo/Reaktive/blob/master/reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Replay.kt#L11) which results in a situation where all subsequent `onNext` calls are happen for newly created instance and lost for an existing one.

### PR DESCRIPTION
**Pull request by arkivanov**
So there was a bug in RxJava's `Observable.replay()` operator, and it was derived by Reaktive. This bug was recently fixed (https://github.com/ReactiveX/RxJava/issues/6920). We need to update our implementation as well.

This also fixes #420.

### CODE REVIEW

File: sample-android-app/src/main/java/com/badoo/reaktive/sample/android/ReaktiveAcitivy.kt [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import com.badoo.reaktive.observable.subscribeOn
+import com.badoo.reaktive.scheduler.computationScheduler
+import com.badoo.reaktive.scheduler.ioScheduler
+import com.badoo.reaktive.single.singleFromFunction
+import com.badoo.reaktive.single.subscribeOn
+
+    @SuppressLint("Registered")
+
+
+    class ReaktiveActivity : AppCompatActivity() {
```
Comment (CherryPerry) [inline sample-android-app/src/main/java/com/badoo/reaktive/sample/android/ReaktiveAcitivy.kt]: What is it?
Why it is in this PR?
What's up with formatting?

File: sample-android-app/src/test/java/com/ReaktiveTests.kt [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+        subject.onNext(0)
+        observer.dispose()
+        disposable.dispose()
+
+        val observer2 = sharedStream.test()
+        sharedStream.connect()
+        observer2.assertValue(0)
+    }
+
+//    @Test
```
Comment (CherryPerry) [inline sample-android-app/src/test/java/com/ReaktiveTests.kt]: ?

File: sample-android-app/src/main/java/com/badoo/reaktive/sample/android/ReaktiveAcitivy.kt (hunk 1 above)
Comment (arkivanov) [reply sample-android-app/src/main/java/com/badoo/reaktive/sample/android/ReaktiveAcitivy.kt]: By accident, removed

File: sample-android-app/src/test/java/com/ReaktiveTests.kt (hunk 2 above)
Comment (arkivanov) [reply sample-android-app/src/test/java/com/ReaktiveTests.kt]: Removed, sorry
