### PR TITLE
Freeze exceptions in observeOn

### LINKED ISSUE #72: Native iOS crash
I have a forked version from a few days ago, so almost master. The following crashes, and in an unpleasant way:

```kotlin
class FailTests{
    init {
        ensureNeverFrozen()
    }

    fun loadData(){
        observableOf(listOf("arst"))
                .observeOn(mainScheduler)
                .subscribe {
                    showData(it)
                }
    }

    fun showData(a: Any){

    }
}
```

The lamba to `subscribe` captures the object instance of `FailTests`, but that has had `ensureNeverFrozen()` called on it, so it should crash. However, rather than report an unhandled exception, we get a low level C++ runtime crash.

```
/Users/teamcity/buildAgent/work/4d622a065c544371/runtime/src/main/cpp/Weak.cpp:35: runtime assert: Incorrect lock state
```

From the stack in xcode

```
#0	0x000000010e87d23e in __pthread_kill ()
#1	0x000000010e8d0c1c in pthread_kill ()
#2	0x000000010e64701d in abort ()
#3	0x000000010a3c52b9 in konan::abort() ()
#4	0x000000010a3c51d3 in RuntimeAssertFailed(char const*, char const*) ()
#5	0x000000010a3c87d8 in WeakReferenceCounterClear ()
#6	0x000000010a3c5d30 in FreeContainer(ContainerHeader*) ()
#7	0x000000010a3d8cdd in LeaveFrame ()
#8	0x000000010a163cf7 in kfun:com.badoo.reaktive.utils.atomicreference.AtomicReference.getAndSet(#GENERIC)#GENERIC at /Users/kgalligan/temp/Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomicreference/AtomicReference.kt:26
#9	0x000000010a372ff1 in kfun:com.badoo.reaktive.scheduler.MainScheduler.ExecutorImpl.Operation.invoke#internal at /Users/kgalligan/temp/Reaktive/reaktive/src/iosCommonMain/kotlin/com/badoo/reaktive/scheduler/MainScheduler.kt:67
#10	0x000000010a372e47 in kfun:com.badoo.reaktive.scheduler.MainScheduler.ExecutorImpl.Operation.$<bridge-UNN>invoke()#internal at /Users/kgalligan/temp/Reaktive/reaktive/src/iosCommonMain/kotlin/com/badoo/reaktive/scheduler/MainScheduler.kt:60
```

The assert is coming from kotlin native's runtime. It looks like something in interop, but that's a complex sequence and a very unexpected error. If you remove `ensureNeverFrozen()` or avoid freezing (https://github.com/touchlab/DroidconKotlin/blob/kpg/reaktive/sessionize/lib/src/commonMain/kotlin/co/touchlab/sessionize/reaktive/ReaktiveExtensions.kt#L65), you avoid the crash.

### PR DESCRIPTION
**Pull request by arkivanov**
Fixes #72

### CODE REVIEW

File: reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CreateDefaultUncaughtErrorHandler.kt [hunk 1]
```diff
@@ -1,6 +1,13 @@
...
 
+import platform.posix.EXIT_FAILURE
+import platform.posix.fprintf
+import platform.posix.stderr
+import kotlin.system.exitProcess
+
 internal actual fun createDefaultUncaughtErrorHandler(): (Throwable) -> Unit =
     { e ->
-        throw e
+        fprintf(stderr, "Uncaught exception: $e")
```
Comment (mk-jones) [inline reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CreateDefaultUncaughtErrorHandler.kt]: Why both the fprint and the printstacktrace? Looks like it could generate messy stacktraces.

Comment (arkivanov) [reply reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CreateDefaultUncaughtErrorHandler.kt]: `fprintf` just prints the title (exception class name and the message, with red colour), `printStackTrace` prints the same title and the stack trace but in regular colour (looks like via stdout).

Comment (mk-jones) [reply reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CreateDefaultUncaughtErrorHandler.kt]: Ah, of course.
