### PR TITLE
Fix warnings

### LINKED ISSUE #759: Warnings related to Kotlin 1.9
```
w: /Reaktive/utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicBoolean.kt:8:53 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicInt.kt:8:53 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicLong.kt:8:53 'AtomicLong' is deprecated. Use kotlin.concurrent.AtomicLong instead.
w: /Reaktive/utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicReference.kt:8:53 'AtomicReference<T>' is deprecated. Use kotlin.concurrent.AtomicReference instead.
w: /Reaktive/utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/clock/DefaultClock.kt:12:17 'getTimeNanos(): Long' is deprecated. Use measureTime() or TimeSource.Monotonic.markNow() instead.
w: /Reaktive/reaktive/src/commonMain/kotlin/com/badoo/reaktive/completable/BlockingAwait.kt:16:15 Returning type parameter has been inferred to Nothing implicitly. Please specify type arguments explicitly to hide this warning. Nothing can produce an exception at runtime.
w: /Reaktive/reaktive/src/darwinCommonMain/kotlin/com/badoo/reaktive/scheduler/MainScheduler.kt:13:33 'AtomicReference<T>' is deprecated. Use kotlin.concurrent.AtomicReference instead.
w: /Reaktive/reaktive/src/darwinCommonMain/kotlin/com/badoo/reaktive/scheduler/MainScheduler.kt:81:41 'AtomicReference<T>' is deprecated. Use kotlin.concurrent.AtomicReference instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/disposable/Various.kt:3:33 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/disposable/Various.kt:9:35 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/disposable/Various.kt:23:31 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/FixedLooperThreadStrategy.kt:3:33 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/FixedLooperThreadStrategy.kt:8:31 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt:11:26 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt:11:33 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt:14:9 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt:14:16 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt:14:24 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt:14:37 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt:26:9 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/LooperThread.kt:26:16 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/scheduler/SchedulerImpl.kt:10:33 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/scheduler/SchedulerImpl.kt:34:35 'AtomicInt' is deprecated. Use kotlin.concurrent.AtomicInt instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/DelayQueue.kt:8:33 'AtomicLong' is deprecated. Use kotlin.concurrent.AtomicLong instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/DelayQueue.kt:98:37 'AtomicLong' is deprecated. Use kotlin.concurrent.AtomicLong instead.
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/ExpirationPool.kt:19:9 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/ExpirationPool.kt:19:16 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/ExpirationPool.kt:19:28 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/ExpirationPool.kt:19:36 Workers API is obsolete and will be replaced with threads eventually
w: /Reaktive/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/ExpirationPool.kt:19:49 Workers API is obsolete and will be replaced with threads eventually
```

And might be other in other modules.

### PR DESCRIPTION
**Pull request by arkivanov**
Fixes #759

### CODE REVIEW

File: utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicReference.kt [hunk 1]
```diff
@@ -5,7 +5,7 @@ import com.badoo.reaktive.utils.InternalReaktiveApi
 @InternalReaktiveApi
 actual class AtomicReference<T> actual constructor(initialValue: T) {
 
-    private val delegate = kotlin.native.concurrent.AtomicReference(initialValue)
+    private val delegate = kotlin.concurrent.AtomicReference(initialValue)
```
Comment (CherryPerry) [inline utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicReference.kt:8]: Do we still need our implementation of `AtomicReference` if Kotlin's one is multiplatform now?
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.concurrent/-atomic-reference/

Comment (arkivanov) [reply utils-internal/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/atomic/AtomicReference.kt:8]: It seems they are still available only on Native.

**Review by CherryPerry — APPROVED** [review]
